name: Epic-sql CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - .gitignore
    tags-ignore:
      - "**"
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    uses: epic-framework/.github/.github/workflows/test.yml@v1
    with:
      archive_artifacts: true
